name: "Evolve EVM"

services:
  ev-reth:
    container_name: ev-reth
    restart: unless-stopped
    image: ghcr.io/evstack/ev-reth:latest
    ports:
      - "9001:9001" # metrics
      - "30303:30303" # eth/66 peering
      - "8545:8545" # rpc
      - "8551:8551" # engine
      - "8546:8546" # ws
    volumes:
      - ./chain:/root/chain:ro
      - ./jwttoken:/root/jwt:ro
      - reth:/home/reth/eth-home
    entrypoint: /bin/sh -c
    command:
      - |
          ev-reth node \
            --chain /root/chain/genesis.json \
            --datadir /home/reth/eth-home \
            --metrics 0.0.0.0:9001 \
            --authrpc.addr 0.0.0.0 \
            --authrpc.port 8551 \
            --authrpc.jwtsecret /root/jwt/jwt.hex \
            --http --http.addr 0.0.0.0 --http.port 8545 \
            --http.api eth,net,web3,txpool \
            --ws --ws.addr 0.0.0.0 --ws.port 8546 \
            --ws.api eth,net,web3 \
            --engine.persistence-threshold 0 \
            --engine.memory-block-buffer-target 0 \
            --disable-discovery \
            --txpool.pending-max-count 200000 \
            --txpool.pending-max-size 200 \
            --txpool.queued-max-count 200000 \
            --txpool.queued-max-size 200 \
            --txpool.max-account-slots 2048 \
            --txpool.max-new-txns 2048 \
            --txpool.additional-validation-tasks 16 \
            --ev-reth.enable
    networks:
      - evolve-network

  local-da:
    image: ghcr.io/evstack/local-da:v0.1.0
    ports:
      - "7980:7980"
    command: ["-listen-all"]
    networks:
      - evolve-network

  ev-node-evm-single:
    image: ghcr.io/evstack/ev-node-evm-single:main
    depends_on:
      ev-reth:
        condition: service_started
      local-da:
        condition: service_started
    ports:
      - "7676:7676" # p2p
      - "7331:7331" # rpc
    volumes:
      - evm-single-data:/root/.evm-single/
    restart: always
    entrypoint: /usr/bin/entrypoint.sh
    command: start
    environment:
      - EVM_ENGINE_URL=http://ev-reth:8551
      - EVM_ETH_URL=http://ev-reth:8545
      - EVM_JWT_SECRET=f747494bb0fb338a0d71f5f9fe5b5034c17cc988c229b59fd71e005ee692e9bf
      - EVM_GENESIS_HASH=0x2b8bbb1ea1e04f9c9809b4b278a8687806edc061a356c7dbc491930d8e922503
      - EVM_BLOCK_TIME=1s
      - EVM_SIGNER_PASSPHRASE=secret
      - DA_ADDRESS=http://local-da:7980 # http://localhost:26658 (Use if not using local-da)
      # - DA_AUTH_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJwdWJsaWMiLCJyZWFkIiwid3JpdGUiXSwiTm9uY2UiOiJQcEswTmhyWi9IY05NWkVtUG9sSXNpRTRDcUpMdE9mbWtBMW0zMWFUaEswPSIsIkV4cGlyZXNBdCI6IjAwMDEtMDEtMDFUMDA6MDA6MDBaIn0.gaWh6tS6Rel1XFYclDkapNnZlaZVjrikCRNBxSDkCGk
      # - DA_NAMESPACE=00000000000000000000000000000000000000000008e5f679bf7116c1
    networks:
      - evolve-network

volumes:
  evm-single-data:
  reth:

networks:
  evolve-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
